name: Server-CI

on:
  pull_request:
    branches: ['main', 'dev']
    types: [opened, synchronize, reopened]
    paths:
      - server/**

jobs:
  server-ci:
    defaults:
      run:
        working-directory: server

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Copy yml
        env:
          BE_APPLICATION_YML: ${{ secrets.BE_APPLICATION_YML }}
          BE_APPLICATION_PROD_YML: ${{ secrets.BE_APPLICATION_PROD_YML }}
        run:
          echo $BE_APPLICATION_YML | base64 --decode > src/main/resources/application.yml &&
          echo $BE_APPLICATION_PROD_YML | base64 --decode > src/main/resources/application-prod.yml

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build Gradle
        run: ./gradlew build
